id: IF0ACE577
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:49:25+00:00'
last_modified: '2022-06-08T02:48:57.987725+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30463
  title: བོད་ཀྱི་གནའ་རབས་རྩོམ་རིག་གི་རིགས་དང་ལུས་ཀྱི་རྣམ་གཞག་ཚངས་པའི་ཚད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '3582':
      image_group_id: I1KG1830
      title: ''
      total_pages: 190
      order: 1
      base_file: 3582.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
