id: P005400
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30463
  title: བོད་ཀྱི་གནའ་རབས་རྩོམ་རིག་གི་རིགས་དང་ལུས་ཀྱི་རྣམ་གཞག་ཚངས་པའི་ཚད་ཡིག
  author: ''
  volumes:
    4cb6c8d2bd3c44118034401f017de553:
      image_group_id: I1KG1830
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
